### ISSUE TITLE
Ctrl+Alt does not work in Linux, but AltGr works

### ISSUE THREAD

**Issue by elmicha** [donid/akuhell#1]
Thank you for your great project! 

All the Ctrl+Alt combinations of the German keyboard do not work on Linux (even on a normal keyboard), but I could easily change akuhell.h so it uses AltGr instead.  I added `altGr = 64` to KeyModifier, replaced `(KeyModifier::leftCtrl|KeyModifier::leftAlt)` with `KeyModifier::altGr`, and added these lines to Keyboard_write():

```
  if ((modifier & KeyModifier::altGr)==KeyModifier::altGr)
  {
    Keyboard.press(KEY_RIGHT_ALT);
  }

```
I read somewhere that AltGr did not work - but now with HID-Project 2.4.4 and Arduino 1.8.1 it works.

**Comment by donid** [comment]
Great to hear that the project is useful to you.

I tried your modifications and they worked for me too. (All my physical machines use Windows, but I have an XUbuntu VM in VMWare). Surprisingly the new code seems to also work with Windows. I am a bit confused that `Keyboard.press(KEY_RIGHT_ALT)` can be used as AltGr... (I haven't worked in this area for five months - so maybe I have forgotten some details in the meantime).

I want to do a bit more testing and if that's successful, I will commit your modifications to the repository.
